### PR TITLE
Fix display

### PR DESCRIPTION
**Pull request by QuentinRillet**
https://github.com/BabylonJS/Documentation/issues/705

### CODE REVIEW

**Comment by deltakosh** [comment]
Do we need to run the script again or will it update when I will push on prod?

**Comment by QuentinRillet** [comment]
Yes, it is necessary to restart the script for the compilation of the documentation. I only committed the script modification.

**Comment by deltakosh** [comment]
Do you mind generating it?

**Comment by QuentinRillet** [comment]
Yes, I do it quickly

**Comment by QuentinRillet** [comment]
In fact it is automatically generated on the server at the time of deployment. You can merge on the prod branch :) @deltakosh

**Pull request merged**
