### PR TITLE
Update list.json

### PR DESCRIPTION
**Pull request by NRABrasil**
Inserted Water Float sample

PS: I do not know the size and how to send a new icon image!

### CODE REVIEW

**Comment by deltakosh** [comment]
For the images you have to save it in that folder:
https://github.com/BabylonJS/Documentation/tree/master/examples/icons
(same size as others)

**Comment by NRABrasil** [comment]
Ok David I will do it.

Thanks

*Nelson Rodrigues Alves*
*Multimedia/Game Designer*
*+55(31)9999 2979*

* iProjects *
www.iprojects.com.br





Em seg, 11 de mar de 2019 às 12:30, David Catuhe <notifications@github.com>
escreveu:

**Comment by NRABrasil** [comment]
David,
I tried to upload the new icon but received this message.
Uploads are disabled.

File uploads require push access to this repository.
So, I am sending it attached! And I will do a new PR to change the icon
name, ok?

Thanks


*Nelson Rodrigues Alves*
*Multimedia/Game Designer*
*+55(31)9999 2979*

* iProjects *
www.iprojects.com.br





Em seg, 11 de mar de 2019 às 12:43, Nelson Alves <
nelson.alves@iprojects.com.br> escreveu:

**Comment by deltakosh** [comment]
actually you can jsut fork the repo and do a PR from there
(or send me the image :))

**Pull request merged**
