### PR TITLE
Occlusion query

### PR DESCRIPTION
**Pull request by IbraheemOsama**
Documentation for PR https://github.com/BabylonJS/Babylon.js/pull/2692

### CODE REVIEW

**Comment by IbraheemOsama** [comment]
@deltakosh  It took more than few hours but I caught the train :)

**Comment by deltakosh** [comment]
No worry:)
Abstract mesh.md is an auto generated file. THe best option will be to move this content directly in the TS file as comments or directly into the new page you created

**Comment by IbraheemOsama** [comment]
I removed my edits from Abstract mesh and will create a PR on babylonjs to update AbstractMesh class

**Comment by deltakosh** [comment]
Thanks!

**Comment by deltakosh** [comment]
Don't forget to give you some credits in the what's new :)

**Comment by IbraheemOsama** [comment]
@deltakosh  Should I update it my self, just thought you're the one who picks what to be there and what is not :D  ?

**Pull request merged**
