### PR TITLE
Stubs remove, offsite tuts list add

### PR DESCRIPTION
**Pull request by Wingnutt**
Stubs remove, offsite tuts list add

I imagine it is a bit scary for curators to see a complete change-out of statics.json, instead of seeing a list of edits to the old one.

But, I did the build at home, using the new statics.json, and with all the stub files removed, and with the list installed in generals... and it was error free and looked fine.
I have good confidence in my _new_ statics.json.  I think it's fine.  :)  (I'm still scared, though)

### CODE REVIEW

**Comment by deltakosh** [comment]
So I can see that you removed stubs but I cannot see the new page

**Comment by Wingnutt** [comment]
Yep, I screwed up.  I put "creating a convincing world" stub into 
generals/general, instead of offsite_tutorials_list.md

Reject the PR, I'll fix and new PR.  Sorry.

Darn.

**Comment by Wingnutt** [comment]
Fixed here... I think.  Not sure if I can add them to my PR, or what happens now.

**Comment by Wingnutt** [comment]
If you want me to cancel first PR and re-PR, tell me so.  I kept it open.  Perhaps the fixes are automatically included.  (scared)

**Comment by deltakosh** [comment]
yep this is fine. I'll merge and start a build to see the result live

**Comment by Wingnutt** [comment]
Yay, build might have worked!
Notice that our _title_ underscores got shortened, so we lost the widened column.  hmm.
Thanks for your help/work/tolerance, DK.

**Comment by Wingnutt** [comment]
Table is not centered in screen, either.  hmm.  Narrow and left-justified.  I will study why.

**Comment by deltakosh** [comment]
Ping @temechon

**Pull request merged**
