### PR TITLE
Suggesting a change to typedoc

### PR DESCRIPTION
**Pull request by RaananW**
Typedoc can include all modules (including the viewer, loaders, serializers, GUI.

This is just a suggestion (which changes the way typedoc was generated until now). It will help Viewer devs as well as Babylon devs.

### CODE REVIEW

**Comment by RaananW** [comment]
See https://deploy-preview-1139--babylonjsdoc.netlify.com/api/

**Comment by RaananW** [comment]
Note that those are the latest declarations (and not 3.2). I just wanted to ask if it makes sense to do that

**Comment by deltakosh** [comment]
We are already pointing to3.3 but we need to clean the d.ts to remove _functions.
also I would like to point to babylonjs directly when entering the api doc

**Comment by deltakosh** [comment]
also the "babylonjs" or "babylonjs-loaders" should be removed

**Comment by RaananW** [comment]
The declaration file was 4 months old, so I assumed it was still 3.2
I can set the link to https://deploy-preview-1139--babylonjsdoc.netlify.com/api/modules/babylon

the "babylonjs" is a module, I will see how I can remove those string-based modules.

**Comment by deltakosh** [comment]
nope it was 29days old:) I update them when we reach stable API for new features

**Comment by RaananW** [comment]
29 days, 4 months, totally the same 😉 
Understood, I will take care of those issues

**Comment by RaananW** [comment]
_ functions are hidden using the `@hidden` tag, default link is to the babylon module

**Comment by deltakosh** [comment]
unfortunately https://deploy-preview-1139--babylonjsdoc.netlify.com/api/ still points to a wrong entry :(

**Comment by RaananW** [comment]
the direct link will point to the globals, but the menu items always point to the babylon namespace
If you limit the namespace to BABYLON, lik it was until now, the other namespaces (like the viewer) are ignored

**Comment by deltakosh** [comment]
Well I completely get the problem but the fix is not satisfying :(

**Comment by deltakosh** [comment]
Where are we with this one? I think we said offline that the drawback of having all modules is acceptable as we make the API tab point to the right one

**Comment by RaananW** [comment]
I didn't merge this yet because I wanted to find a way to use the gulp-generated declaration instead of changing the grunt prices of building the docs. I'll finish this one soon.
Unless you think it's fine pushing here the full declaration of all libraries?

**Comment by deltakosh** [comment]
There is no rush :)

**Comment by deltakosh** [comment]
Closing for now.
Let's revive it when we can:)

**Pull request closed without merging**
