### PR TITLE
Temporary Folder and Page

### PR DESCRIPTION
**Pull request by BabylonJSGuide**
Have been talking to @PirateJC about future upgrade to docs. In particular about new beginners pages. The added temp page is for the purposes of clarification of my suggestion. It is a mock up based on the current structure and so does not have the side bar navigation panels we talked about.  It is there for discussion only and hopefully, I have made it only directly available through the address https://doc.babylonjs.com/beginners/hello_world.

Can delete completely after discussion.

### CODE REVIEW

**Comment by sebavan** [comment]
Adding @PirateJC  for review

**Comment by BabylonJSGuide** [comment]
Would this be better done in a separate branch or would it not then be possible to have live access to suggested pages?

**Comment by sebavan** [comment]
This is perfect as it is @BabylonJSGuide but I added @PirateJC just for a quick overview as you discussed with him about this.

He shall be up in about 5 hours with the timezone diff :-)

**Comment by deltakosh** [comment]
I'm merging and we can change that it in the future ;)

**Pull request merged**
