### PR TITLE
Added Parallel Lines

### PR DESCRIPTION
**Pull request by BabylonJSGuide**

### CODE REVIEW

**Comment by BabylonJSGuide** [comment]
@TrevorDev @RaananW please review changes to joints.md from commit d86081b above. 

The truth of the following section from `A motor requires a target speed... to .... The table below`
relies on OimoJSPlugin lines

```
    public setMotor(joint: IMotorEnabledJoint, speed: number, maxForce?: number, motorIndex?: number) {
        if (maxForce !== undefined) {
            Logger.Warn("OimoJS plugin currently has unexpected behavior when using setMotor with maxForce parameter");
        }
```
being change to something like
```
    public setMotor(joint: IMotorEnabledJoint, speed: number, maxForce?: number, motorIndex?: number) {
        if (maxForce !== undefined) {
            maxForce = 1e6;
        }
```
(Please check accuracy of that)

**Comment by BabylonJSGuide** [comment]
@TrevorDev @deltakosh I know the title is misleading but it was still open when I changed the joints.md page. Is it that you are waiting until all issues with oimo.js are completed? I believe these changes to the docs reflect the current position with all the engines. I will make any changes as necessary as plugins are updated

**Review by TrevorDev — APPROVED** [review]
@BabylonJSGuide the last change I made to oimo for now is https://github.com/BabylonJS/Babylon.js/pull/5819/files . Is this what you were expecting?

Otherwise i think this pr can be merged

**Comment by BabylonJSGuide** [comment]
@TrevorDev as expected thank you.

**Comment by deltakosh** [comment]
Thanks a lot guys!

**Pull request merged**
