### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by RaananW**
Unneeded files removed

grunt serve now watches for changes and reloads the static html server

TODOs:
* ~make sure redirects work like in netlify~
* ~make the watch-tasks update only the changed files.~
* ~`#` links in classes~
* allow configuration of index deletion queries

Please leave this open for now, until the TODOs are done.

### CODE REVIEW

**Comment by deltakosh** [comment]
Excellent!
I need to fix the deep link on classes.pug
I want user to copy paste a link with # and be able to link a method or property

**Comment by RaananW** [comment]
I will add that to the TODO list :)

**Comment by deltakosh** [comment]
I'm on it right now:)

**Comment by RaananW** [comment]
I did nothing with the classes pug, so I won't have any merge problems. go right ahead :)

**Pull request merged**
