### PR TITLE
BabylonJS Editor Toolkit - Starter Documentation

### PR DESCRIPTION
**Pull request by MackeyK24**
Initial Toolkit Documentation

### CODE REVIEW

**Comment by MackeyK24** [comment]
Yo @deltakosh ... You can publish the toolkit starter documentation when you see fit :)

**Comment by MackeyK24** [comment]
Hey @deltakosh ... Can you please change the unity section of statics.json 'Export Panel'  to 
'Export Panels' ... I use that page to describe all the export panel sections. So please make plural :)

**Comment by deltakosh** [comment]
just edit this file:
https://github.com/BabylonJS/Documentation/blob/master/data/statics.json

**Comment by MackeyK24** [comment]
If you mean simply change the statics.json in the same project data folder i forked, then commit that as a PR...I tried that before and got not write access to statics.json

**Comment by deltakosh** [comment]
There is no write access or whatever on github :)
You can also edit it directly on the site here

**Comment by MackeyK24** [comment]
Ok... that worked this time :)

**Comment by deltakosh** [comment]
see :) thanks by the way

**Pull request merged**
