### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MackeyK24**
Initial toolkit documentation - under construction

### CODE REVIEW

**Comment by MackeyK24** [comment]
Hey Delta... I am trying to upload the starter docs for the toolkit. I guess i dont have rights to modify the statics.json and the original unity.md

Can you please take care of that :)

**Comment by deltakosh** [comment]
There is no right on files. You should be able to modify all of them (just do not forget to do a git pull first)

**Comment by deltakosh** [comment]
Ping @babylonjsguide for review

**Comment by deltakosh** [comment]
I will do the PR

**Pull request closed without merging**
