### PR TITLE
VR tutorial

### PR DESCRIPTION
**Pull request by ashanhol**
Created a VR tutorial with accompanying playground code to remedy #628. Feedback is welcome. 

@deltakosh, @Temechon, @BabylonJSGuide

### CODE REVIEW

**Comment by deltakosh** [comment]
Cc @davrous for review

**Comment by deltakosh** [comment]
Looks fantastic to me

**Comment by davrous** [comment]
Hello,

Thanks for submitting! A couple of feedback:

- when attaching a sound to a mesh, it automatically convert to a spatial sound. No need to set it in the options properties then even if, of course, this works too. 
- when switching to VR via the createDefaultVRExperience feature, I'm switching the activeCamera from the deviceOrientation to either WebVR or VRDeviceOrientation. This means that the code can't attach the reticule to activeCamera as this one will change based on context.

I've tried to create an update of the code to show you a possible solution: https://www.babylonjs-playground.com/#KJ8ZRZ#1 but it's not perfect as the activeCamera could also become a VRDeviceOrientation one. I need to update the code of the VRHelper to add a function to return the current active type of VR camera to have a generic code.

I'm then not covering properly the use case you've created. Thanks then ;)

**Comment by deltakosh** [comment]
Up?

**Comment by deltakosh** [comment]
@ashanhol?

**Comment by ashanhol** [comment]
My apologies for the delayed response, I've been traveling and OOF. 
I sent @davrous an email replying to his comment above but never received a reply, copying here. 

I checked out the code you wrote for the possible solution, but reticle.parent = scene.VRHelper._webVRCamera; still doesn’t seem to be parenting properly since it’s still not moving with the camera. I had noticed this problem, but it seemed to work with BABYLON.WebVRFreeCamera so I had assumed that perhaps I had been doing something wrong. The documentation for createDefaultVRExperience() is minimal so I wasn’t sure what the protocol was for using it, but it was how you enabled MR in your //Build videos so I included it.  
How do you suggest I edit it for the time being?

**Comment by ashanhol** [comment]
Added VRHelper code per @davrous's suggestion, reticle now parents correctly. :)
Also included update about spatial sound.

**Comment by deltakosh** [comment]
Looks good to me. Just waiting for @davrous validation

**Pull request merged**
