### PR TITLE
Beginning documentation of the BabylonJS Editor V2

### PR DESCRIPTION
**Pull request by julien-moreau**

### CODE REVIEW

**Comment by deltakosh** [comment]
Should we name it v2 or just remove the previous one and only keeps this one? I don't think we need to keep both

**Comment by julien-moreau** [comment]
That was just to keep backward compatibility (if someone started working with the V1).
I'm for removing the V1 documentation, do you thing that the V2 should be available at editor.babylonjs.com instead of editor.babylonjs.com/v2 ?

**Comment by deltakosh** [comment]
Yeah!

**Comment by julien-moreau** [comment]
Let's go ! =D

**Comment by julien-moreau** [comment]
Done ! And available at http://editor.babylonjs.com/

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
It's a go!!!

**Comment by julien-moreau** [comment]
=D

**Pull request merged**
