### PR TITLE
TOC to LT (#1)

### LINKED ISSUE #1860: Odd paragraph break in About101
The third full paragraph has a sentence fragment that appears as a full paragraph. This was added by eb2480af4aeaf8ed973bce833c31a416a5c811ca with the comment "Fixed broken layout (the paragraph after PG example was too wide)." 

First, I don't understand how to generate the "eye" link that creates an Iframe. 

Second, we should find a way to show the link without the sentence fragment being on its own line.

### LINKED ISSUE #1861: Explain or reference 'UV' early
https://doc.babylonjs.com/babylon101/discover_basic_elements#face-colors-or-uv references "UV" but does not describe it. It would be helpful to have at least an early reference to something like https://en.wikipedia.org/wiki/UV_mapping, if not a brief description.

The same issue exists at https://doc.babylonjs.com/how_to/createbox_per_face_textures_and_colors.

### LINKED ISSUE #1862: Use different glyphs for open/close of table of contents
I'm used to arrows taking me to another location. I'm used to the caret or circumflex character ('^') as open/close for an accordion style element.

### PR DESCRIPTION
**Pull request by JarodO**
* update to camera

* typo

* formatting

* Controller support

* Move to the real colors ;D

* features manager es6 import

* link update

* Fix #1862

* Fix #1861

* Fix #1860

* Changed "Table of contents" to "Lesson Topics"

It's more intuitive to call the list of sections for a single lesson to be called "Lesson Topics" because "Table of contents" usually
refers to the list of lessons, not the list of things in  a lesson.

Co-authored-by: Raanan Weber <raananw+github@gmail.com>
Co-authored-by: David Catuhe <david.catuhe@live.fr>

### CODE REVIEW

**Comment by deltakosh** [comment]
This PR contains too many unnecessary changes. It should just focused on your changes :)

**Comment by deltakosh** [comment]
Up?

**Comment by jgfoster** [comment]
@JarodO, to facilitate easier discussion and merging it is customary to make many small changes rather than one large change. In this case I'd suggest that you withdraw/delete the PR and create a branch with a PR for each issue. I can work with you on it if you have questions. Thanks!

**Comment by JarodO** [comment]
I'm finally going to do something about that.

**Pull request closed without merging**
