### PR TITLE
Particle cone sphere

### PR DESCRIPTION
**Pull request by IbraheemOsama**

### CODE REVIEW

**Review by BabylonJSGuide — CHANGES_REQUESTED** [review]
In the `How can I do this ?' heading the `this` refers to creating particles. A box is mentioned because a box mesh is used as an emitter. It is not a reference to creating a particle box shape.  To stop any confusion please change this heading from `How can I do box shape ?`.

Suggest `How Can I Create Particles ?`

**Comment by deltakosh** [comment]
Looks good to me

**Comment by deltakosh** [comment]
Up?

**Comment by deltakosh** [comment]
Up?

**Comment by IbraheemOsama** [comment]
Me or him 😄

**Comment by deltakosh** [comment]
lol you :D as @BabylonJSGuide mentioned a tiny change :D

**Comment by BabylonJSGuide** [comment]
@deltakosh suggest accepting as is and I will make the changes I want afterwards.

**Review by deltakosh — APPROVED** [review]

**Comment by IbraheemOsama** [comment]
@BabylonJSGuide @deltakosh sorry guys, was planning to do it today

**Comment by deltakosh** [comment]
no worry at all!

**Pull request merged**
