### PR TITLE
fixed playground search by titles 

### PR DESCRIPTION
**Pull request by ssaket**
It was an index issue xD

### CODE REVIEW

**Comment by RaananW** [comment]
Thanks! I made a few changes and added a few try-catches to prevent this from happening again in #1060

**Comment by ssaket** [comment]
@RaananW  - for the playground tab, the search name is still q.

**Comment by ssaket** [comment]
So, this try {document.getElementsByName('bjsq')[1].value = strQuery;} catch(e) {} will fail

**Comment by RaananW** [comment]
https://github.com/BabylonJS/Documentation/pull/1060/files - playground's template was also changed. so it is now bjsq

**Comment by ssaket** [comment]
Aaahhh... Awesome , in my branch it was showing the old code. time to do pull

**Pull request closed without merging**
