### PR TITLE
change code quote

### PR DESCRIPTION
**Pull request by getzelus**
because bad visualisation online

### CODE REVIEW

**Comment by getzelus** [comment]
Hello, thx for merged it.
When it will be online ? I see that the tutorial page has still this code quote at the bad place.

**Comment by deltakosh** [comment]
We merge every monday

**Comment by getzelus** [comment]
Hello, I dont know why, there is still this bad display :( 
Can u do something ? 

Here is an example of what's wrong now with the tags : 
http://i.imgur.com/yUSyvZR.jpg

**Comment by RaananW** [comment]
Just wanted to update :
it was merged - http://doc.babylonjs.com/tutorials/raycasts

**Comment by getzelus** [comment]
Thank you. 
Can you change the last picture for multipick by the good one ? 

https://cloud.githubusercontent.com/assets/24637259/22629048/61651dcc-ebdf-11e6-86e4-4fdea6f16212.jpg

I don't have the right to upload pictures in img folder.

**Comment by RaananW** [comment]
Done.
Have an interesting day!

**Pull request merged**
