### PR TITLE
P8/adding skeleton viewer & capsule mesh

### PR DESCRIPTION
**Pull request by Pryme8**
Is there anything else I should add or clarify more?

### CODE REVIEW

**Comment by Pryme8** [comment]
```
content/How_To/material/Creating_a_Texture_Package.md
content/features/component/Materials.md
```

How do I resolve this?  Could have sworn I pulled from master.

**Comment by Pryme8** [comment]
weird...

**Comment by Pryme8** [comment]
Is @PirateJC out of town?

**Comment by PirateJC** [comment]
Nope I'm here, will review this shortly.

**Review by PirateJC — APPROVED** [review]
Awesome work @Pryme8 I took a quick cleanup pass at some of the writing in a few of the docs, but other than that it's all good!

**Comment by Pryme8** [comment]
> Awesome work @Pryme8 I took a quick cleanup pass at some of the writing in a few of the docs, but other than that it's all good!

Thank you friend.

**Pull request merged**
