### PR TITLE
Adding note to HDR Rendering Pipeline

### PR DESCRIPTION
**Pull request by julien-moreau**

### CODE REVIEW

**Comment by deltakosh** [comment]
I suggest completely removing it and replacing it by a std pipeline doc ;)

**Comment by julien-moreau** [comment]
I removed the file
You ok to remove or don't remove but just add a link to the standard rendering pipeline ?

**Comment by julien-moreau** [comment]
Cool ! ^^

**Comment by deltakosh** [comment]
thanks a lot

**Pull request merged**
