### PR TITLE
variable name harmonization + Apple exception...

### PR DESCRIPTION
**Pull request by Vinc3r**

### CODE REVIEW

**Comment by Vinc3r** [comment]
also, is this video, from the example playground, open sourced?

https://yoda.blob.core.windows.net/videos/uptale360.mp4

If so, should be better to have it saved inside the BJS website isn'it ? But I don't know who is Yoda.

**Review by deltakosh — APPROVED** [review]
Thanks mate!

**Comment by deltakosh** [comment]
Well not sure..Would love to find a new one honestly

**Comment by Vinc3r** [comment]
@deltakosh I don't find too much interesting CC0 360 videos on the net.

I like this one, funny: https://vimeo.com/207461532

If you're agree about this one, I will make some video cutting to get only a short part of it.

**Comment by deltakosh** [comment]
is it license free?

**Comment by Vinc3r** [comment]
yep, CC0

img

**Comment by deltakosh** [comment]
perfect

**Pull request merged**
