### PR TITLE
new How-To PBR category

### PR DESCRIPTION
**Pull request by Vinc3r**
#1300 

modifying static.json should be enough, right?

### CODE REVIEW

**Review by deltakosh — COMMENTED** [review]
Did you compile and try it locally?

**Comment by Vinc3r** [comment]
I'm afraid not, can give a try (even if building code seems scary to me :-D )

**Comment by deltakosh** [comment]
Haha..no worry..

**Comment by Vinc3r** [comment]
so, after running `grunt serve`, my webpage opened and show me a `/ not found`

my terminal show this:

```
(node:4751) ExperimentalWarning: The http2 module is an experimental API.
Running "connect:server" (connect) task
Started connect web server on http://localhost:8080

Running "open:local" (open) task

Running "watch" task
Waiting...
```

I [followed this](http://www.html5gamedevs.com/topic/16365-contributing-to-documentation-101/?page=1) (except I have direclty get repo from a `git clone` command.
Notice that I'm currently on Xubuntu, but I don't think that matter?

**Comment by Vinc3r** [comment]
em OK, just tryied to come back to the current oline statics.json... and it's working :-p So I've break the doc'.

**Comment by Vinc3r** [comment]
talking too quickly: when I click on menus, same error (ex: `/resources not found`)

**Comment by deltakosh** [comment]
you have to run grunt build first

**Comment by Vinc3r** [comment]
yeah! ok thanks :-p 
I've spotted an error on my side

**Comment by Vinc3r** [comment]
thanks for your help, long time to understand, short time to learn ahah
(this building thing will helps also me a lot for API contributions for example, nice!)

**Comment by BabylonJSGuide** [comment]
modifying static.json should be enough, right?
Probably not there are likely to be links from other pages, eg features, index and maybe others.

You need to search for /How_To/Physically_Based_Rendering with no case sensitivity.

Also need re-direct for external links.

**Comment by BabylonJSGuide** [comment]
By the way though not set against the change, the idea of the categorisation was to keep headings to a minimum (OK not 100% successful) The balance between menu and sub menus is always difficult and quite possibly there may be arguements for a re-categorisation as a whole but as it is I think just pulling out PBR as a separate category is on balance not necessary. PS liked your new image for arcRotateCamera and will listen to arguements for moving PBR

**Comment by Vinc3r** [comment]
ah, totally forgot about the page links issue. And just modifying the statics.json made me an error when doing the `grunt build` saying that PBR/_page_.md doesn't exists, so I create and move to the PBR folder.

And you're right, there are already many submenus, probably confusing. My point about this specific category is that to an artist point of view, PBR is a must-have, and so have to be quickly accessible. So maybe we can use the already existing *material* category instead of *environment*? Or just drop out my suggestion :-p

**Comment by BabylonJSGuide** [comment]
My apologies as I realised that provided the PBR pages stay within the How To section the links will still hold. In order to give PBR more prominence my suggestions are, with a little re-writing, either to have a page in the materials section describing PBR which links to the pages in the environment section or vice versa to move the PBR pages to the material section and still have one page describing PBR in the environment section. Having something in the environment will help those who are used to finding it there. Also you could consider adding a brief mention of PBR in the material page of Babylon 101 with links to the other PBR pages and editing and linking as needed in the environment page under the features sections.  Very pleased that you are taking an interest in the documentation and definitely think it is a good idea that someone for whom PBR is important can improve how PBR is dealt with, especially from an artists point of view.

**Comment by Vinc3r** [comment]
I just notice that url rewriting allow indeed to move a page from one folder to another without affecting links to this page, that's convenient (and no worries, it's normal to discuss about issues which could break some things or logics).

So to resume, instead of new PBR category, we can:

- move [Start with Physically Based Rendering (PBR)](http://doc.babylonjs.com/how_to/physically_based_rendering) into **Material** filter
- move [Master Physically Based Rendering](http://doc.babylonjs.com/how_to/physically_based_rendering_master) into **Material** filter
- extract the [Env map](http://doc.babylonjs.com/how_to/physically_based_rendering#env-map) part from **Start with Physically Based Rendering (PBR)** and create a new page in **Environment** filter, named, for example: **Use a HDR environment (for PBR)**
- search in all `/content/` links to the two current PBR pages, and check if it's talking about env or material, up date link if it's about env

Is that seems OK? It looks like a lot of work for a tiny details actually, but why not? :-p

**Comment by BabylonJSGuide** [comment]
Sounds like a good plan to me

**Comment by Vinc3r** [comment]
ok, I can handle it, but probably not before the next week-end

**Comment by BabylonJSGuide** [comment]
No rush :)

**Comment by Vinc3r** [comment]
(I always panick when a conflict append :D )
still have to create the HDR Env page

**Comment by Vinc3r** [comment]
Ok, I think it should be right now... isn't it?

**Comment by deltakosh** [comment]
I let @BabylonJSGuide decide here

**Comment by BabylonJSGuide** [comment]
Midnight here. Will have a look tomorrow.

**Review by BabylonJSGuide — APPROVED** [review]

**Comment by BabylonJSGuide** [comment]
@Vinc3r well done and thank you

**Pull request merged**
