### PR TITLE
Meshes to Import Started

### PR DESCRIPTION
**Pull request by BabylonJSGuide**
Re issue #1074 I have made a start on such a page. Further comments in the issue.

### CODE REVIEW

**Comment by BabylonJSGuide** [comment]
The 'a few more' commit will all I will be able to do for a day or so.

**Review by deltakosh — CHANGES_REQUESTED** [review]
To get the best rendering possible, I suggest using the defaultenvironement and camera:
https://www.babylonjs-playground.com/#VTP5NT

Thank you so much for your help

**Comment by BabylonJSGuide** [comment]
Can see the idea behind using the default environment and cameras, the code is neat, clear and simple and deals with 'scaling' issues. Will make the changes and will add a section on dealing with scaling issues for users who want to use a one of the other cameras. It took me a while to work out why for example the BoomBox was not appearing and so think it is important to cover this point. Unless I am missing something.

**Comment by BabylonJSGuide** [comment]
Yes I was missing something can get the user to use the scene 'inspector' to check out the camera radius. So will add a section on this instead.

**Comment by deltakosh** [comment]
Thanks you so much!

**Comment by BabylonJSGuide** [comment]
Unless further changes are needed after review I am not intending to make any immediate changes or additions to this page.

**Review by deltakosh — APPROVED** [review]
Perfect!

**Pull request merged**
