### PR TITLE
Improving editor documentation

### PR DESCRIPTION
**Pull request by julien-moreau**
Updated sky material documentation as well

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
Can you check what is failing on the check?

**Comment by julien-moreau** [comment]
Just found:

3:38:00 PM: Failing build: Failed to deploy site
3:38:00 PM: failed during stage 'deploying site': Failed to execute deploy: Error: preprocessing deploy timed out

It is building locally with 0 error :(
Can we re-run the check ?

**Comment by julien-moreau** [comment]
Just found:

3:38:00 PM: Failing build: Failed to deploy site
3:38:00 PM: failed during stage 'deploying site': Failed to execute deploy: Error: preprocessing deploy timed out

It is building locally with 0 error :(
Can we re-run the check ?

**Comment by deltakosh** [comment]
Ok I think it is fine then

**Pull request merged**
