### PR TITLE
Fix typo: is ignore for now -> is ignored for now

### PR DESCRIPTION
**Pull request by Neob91**

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello this file is generated actually. You need to edit the source code comment at the root repo :)

**Comment by Neob91** [comment]
@deltakosh Oh, good to know, I will - thanks!

**Comment by deltakosh** [comment]
Thanks buddy

**Comment by Neob91** [comment]
https://github.com/BabylonJS/Babylon.js/pull/8975

**Pull request closed without merging**
