### PR TITLE
Move Babylon101 and reactjs

### PR DESCRIPTION
**Pull request by QuentinRillet**

### CODE REVIEW

**Comment by mootari** [comment]
What's with all the reformatting that happened in this pull request? Seems a bit opinionated/ out of scope?

**Comment by BabylonJSGuide** [comment]
This happened just after the restructuring of the document into its current format. Part of the re-settling period. Cannot see that this old PR has any bearing on the current situation.

**Comment by mootari** [comment]
I was merely wondering wether the changes were accidental (seeing how log/bjs-doc-error.log was also changed). If that were the case we might have to double down on commit reviews to avoid cluttering the history.

But if those changes were intentional I'd love to know which code style I should adhere to.

**Comment by BabylonJSGuide** [comment]
OK when I saw these commits back in Oct I only considered the positioning of reactjs any other changes I left to QuentinRillet and Deltakosh so I guess I am not the one to actually answer your question. Though because there are several changes going on in the PR I am not very clear which changes you are referring to or what the two code styles are or which you should adhere to.

**Comment by deltakosh** [comment]
Agree with John. 
By the way as you are clearly well involved in the project if you want to define formal rules please go for it;)

**Comment by mootari** [comment]
Just to be clear, I don't mean to rain on anyone's parade, and I don't necessarily think we need a code style at this point.

My concern is that some of the changes in this pull request don't match the described intent, which makes it very hard to `git blame` one's way through the code history. I strongly suggest that we ensure that commits only touch the parts that the issue or pull request intended to change.

To give a better example, this pull request adds the following out of scope changes:
- removes markdown files for 2.5 classes,
- completely reformats statics.json,
- completely reformats several other unrelated files without introducing any functional changes.

This criticism is *not* directed at @QuentinRillet or any other person. I just want to figure out how we can improve the review process in general. I absolutely realize that everyone involved generously takes time out of their day to improve BabylonJS and its documentation for everyone. Let's make it easier for both contributors and reviewers by providing better guidelines. 😃

**Comment by deltakosh** [comment]
No problem :) It was done during a big rework of the doc so we were not focused on clarity of the PR but more on "will everything still work :)"
But now that we have the content we want we will obviously make sure that PR are correct

**Comment by BabylonJSGuide** [comment]
Agree. Perhaps some guidelines in the Read Me file.

**Pull request merged**
