### PR TITLE
Remove duplicate redirect rules

### PR DESCRIPTION
**Pull request by mootari**
A recent pull request added duplicate redirect rules.

### CODE REVIEW

**Comment by mootari** [comment]
@deltakosh Your response time is insane. 😄

**Comment by deltakosh** [comment]
Lol..I have a neural connection to GitHub :D

**Comment by mootari** [comment]
Btw, I just had a script generate some [splats](https://www.netlify.com/docs/redirects/#splats) from the existing rules. Unfortunately it only chopped off 15 of the 155 rules, replacing them with 3 splat rules. I guess those results aren't really worth the added complexity.

**Comment by deltakosh** [comment]
yeah agree :(

**Comment by mootari** [comment]
I've found some dead redirect targets as well, but I don't know where they're supposed to point to:
- /How_To/How_to_use_the_Tags_System
- /How_To/How_to_use_VirtualJoysticksCamera

Any hints?

**Comment by mootari** [comment]
Nevermind, found them.

**Comment by deltakosh** [comment]
Lol you are fast

**Comment by mootari** [comment]
Follow up merge reqest: #735

**Pull request merged**
