### PR TITLE
Development

### PR DESCRIPTION
**Pull request by BabylonJSGuide**

### CODE REVIEW

**Comment by deltakosh** [comment]
Thanks a lot:)we need to do a bit of work to update the search index but we will merge asap

**Comment by QuentinRillet** [comment]
Hi @BabylonJSGuide ,

Could you fix your conflicts before merging?

Thanks !

**Comment by RaananW** [comment]
When everything's ready I will empty the search index, merge, and make sure netlify works correctly.

**Comment by BabylonJSGuide** [comment]
As Temechon requested have been able to sort out conflicts and have corrected a couple of links I found I needed to

**Pull request merged**
