### PR TITLE
starting doc about Blender animations and how to deal with them

### PR DESCRIPTION
**Pull request by Vinc3r**
You can notice I've put example files on this folder: `examples\blender\animations` (blend file, and also BJS files).

Is it the right place to use? If yes, it the link of `examples\blender\animations\babylon-format.zip` will be `http://doc.babylonjs.com/examples/blender/animations/babylon-format.zip` ?

### CODE REVIEW

**Comment by deltakosh** [comment]
Thanks:)
The repo or of the publish website is /public/html
So examples have to go under public/html/examples

**Comment by Vinc3r** [comment]
It seems that due to the `.gitignore` I can't add & commit files into /public/html.

```
!public/html
!public/js
public/html/*
```

But maybe you talking about the Website repo? I just see that we have already this folder `Website\Scenes\Blender` which maybe can be used? If so, the public url to link a file inside this folder seems to be, for example, [http://www.babylonjs.com/Scenes/Blender/blender.blend](http://www.babylonjs.com/Scenes/Blender/blender.blend), right?

**Comment by deltakosh** [comment]
Nope I was mentioning the Doc website.
You can forcefully add files even when they are in the gitignore 
I use tortoisegit for that

**Comment by Vinc3r** [comment]
Is it OK like that ?

**Review by deltakosh — APPROVED** [review]
Perfect

**Comment by Vinc3r** [comment]
Thanks for your patience ;)

**Comment by deltakosh** [comment]
You are kidding me? Thanks for your support man!

**Pull request merged**
