### PR TITLE
Add a tags to banner image and section name

### LINKED ISSUE #1859: Page navigation issues
As I go through the tutorial I'm finding it difficult to navigate. For example, the first page (https://doc.babylonjs.com/babylon101/about101) has a section in the table of contents labeled 'Next' but it has no content and there is no link to the next lesson.

Suggestions:

- Every page have a link back to the top
- Every page have a link to the previous lesson as its first link
- Every page have a link to the next lesson as its last link

### PR DESCRIPTION
**Pull request by PlasmaIntec**
Fixes [#1859](https://github.com/BabylonJS/Documentation/issues/1859)

### CODE REVIEW

**Comment by deltakosh** [comment]
We should also make it centered vertically:
image

**Comment by deltakosh** [comment]
Up?

**Comment by PlasmaIntec** [comment]
Bit of a hack but the links should be centered vertically now

**Comment by deltakosh** [comment]
Like  it! thanks!

**Comment by PlasmaIntec** [comment]
Are you guys running `grunt sass` and `grunt build`? The formatting is currently broken 

image

**Comment by deltakosh** [comment]
On it ;)

**Pull request merged**
