### PR TITLE
Initial Documentation: ClonerSystem

### PR DESCRIPTION
**Pull request by androdlang**
Puh, so much work and I'm in no way a native speaker !
But wiriting docs is a recursive process and there must be a stop condition, I feel it, it is now :)
Cheers

### CODE REVIEW

**Comment by deltakosh** [comment]
Perfect! don't forget to update this file: https://github.com/BabylonJS/Documentation/blob/master/data/statics.json

**Comment by androdlang** [comment]
Hi David,
I'm sorry but I think I'm a bit overchallenged with this statics.json 
<https://github.com/BabylonJS/Documentation/blob/master/data/statics.json>
I guess this is the mapping from the BJS-Doc-View to Github?
At first view I can't see a correlation between all the Items in the 
structure...
foldername??? files??? image???
At the moment I habe no idea how and what I should update here.
Can I do this with the same "easy" method directly from github client or 
must I run a build process??
Again, sorry,I'm stucking,
Greetings, Hans

Am 04.04.2017 um 00:10 schrieb David Catuhe:

**Comment by deltakosh** [comment]
No worry. I'll try to explain how it works :)

You can edit the file in GitHub. Here the entry point for extensions:
https://github.com/BabylonJS/Documentation/blob/master/data/statics.json#L466

You should add a node like the one for Tree generators:
https://github.com/BabylonJS/Documentation/blob/master/data/statics.json#L466

This node must reference all the files you want to display in your doc ;)

**Comment by androdlang** [comment]
Hopefully this is correct...

**Comment by androdlang** [comment]
OK, I think I've got it but now I have a github question:  do I have to 
close the pull request?

I didn't find a button to submit, so I closed but I have the option to 
reopen?

What shall I do?


Am 04.04.2017 um 00:49 schrieb David Catuhe:

**Comment by androdlang** [comment]
Oh, I see a red cross near Update statics.json "Deploy preview failed"

**Comment by androdlang** [comment]
OK, I had overseen 2 kommas, fixed

**Comment by deltakosh** [comment]
do nothing :)
we will review it soon

**Comment by deltakosh** [comment]
I fixed it

**Pull request merged**
