### PR TITLE
modified search input q to bjsq

### PR DESCRIPTION
**Pull request by ssaket**
@deltakosh - Hi David, It's me again !

For generating the api templates, we don't use the classes.pug anymore.  
Sorry, I have very little knowledge of grunt and typescript. I have tested the "search bar" for all other tabs, it works fine :)

Question here - In the playground tab ( http://doc.babylonjs.com/playground/) , first tab's search is returning null on every query; Is this the expected behaviour or should I look into this ?

### CODE REVIEW

**Comment by RaananW** [comment]
Hi,

No, this is not the expected behavior :smile:

Would be great if you can look into it!

**Comment by ssaket** [comment]
thanks @RaananW :)
I don't think its because of "bjsq" change ; playground.pug has an independent search inputs for all three form(titles, tags, code) and corresponding script files.

Should I create a new issue ? What is the result expected? Is it the links of playgrounds ?

**Comment by RaananW** [comment]
It should be the same as the other searches, but with title instead of tags.

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
Thanks a lot!

**Comment by RaananW** [comment]
I found the reason and will fix it in the next commit. thanks a lot for your time :smile:

**Pull request merged**
