### PR TITLE
Small fixes in how_to_start.md

### PR DESCRIPTION
**Pull request by ashanhol**
Small spelling/grammar fixes, included link to Docs contribution.

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello! and thank you:)
we are in the middle of a big rework.
So I may wait a bit before merging your PR
ping @BabylonJSGuide fyi

**Comment by deltakosh** [comment]
And thanks a lot for this PR btw

**Comment by deltakosh** [comment]
Ping @temechon as well

**Comment by deltakosh** [comment]
Hey sorry but we may have introduced some conflicts :)

**Comment by QuentinRillet** [comment]
Hi @ashanhol,

I can see your PR contains some conflicts, do you mind fixing it please ? Or do you want me to close the PR and move it manually ?

**Comment by ashanhol** [comment]
Ok, merged in the latest master. Seems the only conflict was an error log? 

@deltakosh, @QuentinRillet, @Temechon, @BabylonJSGuide

**Comment by QuentinRillet** [comment]
Thank you !

**Pull request merged**
