### PR TITLE
Cleaning and adjusting layermask and PG tuts

### PR DESCRIPTION
**Pull request by Wingnutt**

### CODE REVIEW

**Comment by deltakosh** [comment]
Thank you...I really appreciate your work!

**Comment by Wingnutt** [comment]
Thanks for the thanks.  It's my pleasure.  :)

The pictures for the PG tutorial... were moved to a different folder at urbanproductions.com.

The pictures won't work @ http://doc.babylonjs.com/generals/The_Playground_Tutorial until after a new build. SO, maybe build before July.  :)  thx

**Comment by deltakosh** [comment]
Should be good in less than 10minutes

**Comment by ghost** [comment]
@deltakosh  Doc is still down! Sorry, but I don't know how I could help more than warning you in every possible way I can!

**Comment by deltakosh** [comment]
Trying again

**Comment by Wingnutt** [comment]
Oh, sorry, I'm slow to read your comments.  All looks fine to me.  Was there trouble?

I wasn't in a hurry.  Build in 2 weeks = fine.  Really.

Nobody ever reads the playground tutorial, anyway.  The playground is very intuitive.  It teaches itself

Thanks for the notifications, and for trying those builds.  Was it refusing to build?  I hope I didn't break something.  :o

**Comment by deltakosh** [comment]
No worry everything is fine:)

**Pull request merged**
