### PR TITLE
Renaming the first tutorial

### PR DESCRIPTION
**Pull request by Wingnutt**

### CODE REVIEW

**Comment by deltakosh** [comment]
Good start :) but you also need to rename the real file

**Comment by Kimoen** [comment]
In the folder 'content\tutorials\01_Play_Pen', rename the corresponding MD file and you're done!

**Comment by deltakosh** [comment]
Perfect! Thanks!

**Comment by Wingnutt** [comment]
Thank you!
Now, to do the rest of them, I could... hmm... clone the repo into my Wingnutt account, change all the names, edit the json to match, then do a single PR for all of them, yes?  Bad idea?  (thx)

**Comment by deltakosh** [comment]
Nope this is exactly what you should do:)

**Comment by Kimoen** [comment]
It's a perfect idea actually :)

**Comment by Wingnutt** [comment]
Hi guys, thanks!  I should repair all the 'next tutorial' links at the bottom of each tutorial, too?  Or remove them?  Thoughts?  (thx)

**Comment by Kimoen** [comment]
I vote to update them.

**Comment by deltakosh** [comment]
Same here

**Comment by Wingnutt** [comment]
Roger... will do.

**Comment by Wingnutt** [comment]
Crap, sorry guys, but maybe you can help me easier than finding the answer on the web.  It says my current doc repo @ github wingnutt is 52 commits behind.  I can't seem to find a refresh, but there IS a "compare" and a "pull request" beside that notification.  Could you hold my puppy paw a bit longer? (thx)

**Comment by RaananW** [comment]
git checkout master
git fetch BabylonJS
git merge BabylonJS/master

**Comment by RaananW** [comment]
(In a git console, of course :) )
and afterwards:
git push

**Comment by Wingnutt** [comment]
All sorts of familiar faces in here.  :)  Not sure I understand.  I would prefer not to use a local repo.  I would like to update Wingnutt (my git user name) /Documentation from BabylonJS/Documentation (master or production).  I was hoping to do it all at github.  Possible?  (thx)

**Comment by RaananW** [comment]
I just realized you are using github's web interface.
go to your local repository (Wingnutt/Documentation) and click create pull request.
in the left box, choose Wingnut/Documentation.
then two boxes will vanish. click on the link "compare across forks" (the upper sentence)
now choose BabylonJS/Documentation at the 3rd box.
make sure the 2nd and 4th are saying "master".
Then create the pull request and merge it

**Comment by Wingnutt** [comment]
Looking good, thanks!  Now it says "This branch is 1 commit ahead of BabylonJS:master.".  I suppose that is fine.  Does this cause any workload to curators?  Did someone need to approve this "refreshment"?  I hope not.  It sure seemed like a bunch of activity for a "refresh me".  :)

**Comment by RaananW** [comment]
the one commit ahead is your pull request commit. It is perfectly fine.
This is git's way :) it will eventually make sense.

**Comment by Wingnutt** [comment]
Still two questions.  Did anyone besides me... need to approve my refreshing pull? (that sounds dirty somehow)  :)

And... do you know if I can sync my online repo, to the BJS master... so it stays fresh all the time?
(thanks again)

**Comment by RaananW** [comment]
The PR you just created was on your local repository, which you alone control (you have write rights). 
What you just did was taking all of the commits missing in your repository and merged them.
You usually do the other way around - PR to the BJS repository. There you have no write rights, so it needs to be approved by an admin.
Your local repository stays as fresh as you keep it. The best way is to actually use a git command line (or a git tool like Github for windows). But if you want to use the web interface alone, this will be the only way (that I know) to keep your repository synced.

**Comment by Wingnutt** [comment]
I understand.  But I heard somewhere that pushes (from my home repo) were not allowed.  Do I push it to the Wingnutt git account, and then send a PR to the curators asking them to pull my edits from the online Wingnutt repo at github?  

It seems... that if I request that curators pull from my home repo, I would need a server and to make my home repo... shared.  I really don't want to run a server or be concerned that my home computer is shut-off when curators want to do a remote pull from me.

I have much to read/learn.... sorry for the puppy questions.

**Comment by RaananW** [comment]
not sure what your "home repo" is.
This is a very simplified explanation:
you have your online form (repository) under Wingnutt/Documentation. This is yours alone to control. You can create branches there, you can edit files, you can "download" (clone in gittish) it to your local computer and work on it there. Syncing between the clone (on your computer) and your repository (on github) is done using pulls and pushes. You don't need any pull request there.
When making changes on your repository (whether online or on your computer) you create commits. those commits can later be sent to Babylon's repository using pull requests. 
A best practice to achieve a clean pull request from your repository (to update BJS's documentation, for example) it to create a branch of your master and edit the files there. A branch is a local copy of (usually) your master. This way you keep your master clean and can make changes without the fear of doing anything wrong. One you are satisfied with the content of this branch (you made changes to files you wanted to change) then you create a pull request from your branch to Babylon's master. The admins will then see the files you changed and decide whether or not you changes are good. Afterwards you can close your branch and go back to your master, to continue working on other files.
My recommendation is - always keep your master synced (with the method I showed you before), branch from the master, create your changes, and send a pull request.
Don't fear of making a mistake. If you made a mistake in a branch, you can simply delete it, go to the master, and start again.
You have no need of a server or anything of that sorts. Your repository is public. Babylon can pull your changes whenever the admins want. But it needs your help to keep those requests structured. This is a pull request. You send a pull request from your online repository (the one already on your server), so your local computer is totally not involved in this.
I hope it made more sense than confusing you! :smile:

**Comment by Wingnutt** [comment]
Ok, thanks, very good.  Home repo = the clone of docs repo that I have on my home computer.  

If I asked the curators to pull from my home computer... I WOULD need a server and WOULD need to set that folder as shared, I suspect.  Having anything visit and get files from my home computer... 1. scares me.. and 2. requires that my computer stay powered and its server stay running.  

update: I now understand that it never happens that way.  Good. :)

The only reason I maintain a fresh repo on my home computer... is to do builds of edits I make... to make sure the HTML version looks good after the edit of the md.  Strictly html test-viewing.  

After html test-viewing, I visit the github web interface, make sure it is fresh, make sure that the file I edited at home... hasn't changed since I started the edit... then paste-in the edited .md at the web interface, then do the PR from there.

Thanks for all the help, R, T, and DK.

**Comment by RaananW** [comment]
I am not sure you understood what I said.
but! do whatever makes you feel right :smile:
just a final note - you don't send PRs from your home computer. even when doing that, you still first upload the data to your own repository on github. Then and only then will the PR be sent to the onlien repository of Babylon.
No one, at any point, has access to your local files.

**Comment by Wingnutt** [comment]
No, I understand.  You were telling me good housekeeping ideas for my online repo at github.
And yes, that is good info about... things go to my Wingnutt fork first, and then the pulls over to production... come from there.

This 'push' you spoke-of... pushes to Wingnutt account, not to BJS account, and that's why it is allowed.  I think DK told me "no pushes" but he was talking about pushing directly to BJS git account... and not to Wingnutt git acct.

I'm curious which part was misunderstood.  :)

**Comment by Wingnutt** [comment]
I don't need to keep my local (home) repo sync'd.  I will do fresh clone to home... before I start editing an md (also edited at home, with my MarkdownPad2 github-flavored editor).  I would do a docs build of that edited md (at home), to make sure its html looked ok.  THEN, without delay... I head to Wingnutt online acct... refresh my Wingnutt online repo, then make sure that the file I am editing... hasn't changed since my clone-to-home... then fork my master as you suggested, choose the file to edit, paste in the md text that I made at home, save the edit, do the PR.

Workflow hell, eh?  If I don't inspect the html version before I come online to github... the html could look like crap after the commit, which means I would need to edit again, and again, and again, until the html looked nice.  Lots of work for curators... not wise.

**Comment by Wingnutt** [comment]
Tiny, simple edits... probably don't need all the BS that I talked-of, and can be done completely at github web interface, likely.  Temechon and I did one like that, recently.   Smooth and easy.

**Comment by Wingnutt** [comment]
ok. I guess we're done here.  :)

**Comment by Wingnutt** [comment]
Guys, I might have pushed a bad button yesterday.  Please delete/ignore any git stuff from me... while I practice.  
I was using the "update my master from bjs master" thing that Raanan taught me, but I forgot to select MY repo in the **left** box, and BJS in the **right** box.  I had them reversed, so I think my pull/merge... went the wrong direction.
Thanks for your patience, guys.

**Comment by Wingnutt** [comment]
Would anyone like to help with my Permission denied (publickey) (in git bash)?

http://urbanproductions.com/wingy/babylon/misc/perm_denied.txt

Advice VERY welcome (thx).  It's still the first day, though, so I'm begging for help a bit early.  I have much more reading and bleeding to do, yet.  :)  

"The agent has no identities."  (ssh agent).  I think THAT might be something important and broken.  :)

**Comment by Wingnutt** [comment]
Yay!  http://urbanproductions.com/wingy/babylon/misc/perm_granted.txt  I am SO PROUD of me.  heh
I have ssh identity!  I am SOMEBODY!
(no?  Still not yet? _nod_)  :)

**Pull request merged**
