### PR TITLE
cornell box was broken since BJS v4

### PR DESCRIPTION
**Pull request by Vinc3r**

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]
What was the issue?

**Comment by Vinc3r** [comment]
it was about meshes with multimaterials, which are converted in gltf as one mesh per materials, children of an empty root mesh.
 - on BJS v3, root mesh (named _myObject_) was part of the className "Mesh" (but haven't any geometry), and its children was named _myObject\_0_, _1_, _2_, etc
- on BJS v4, root mesh is part of the className "TransformNode", and its children are named _myObject\_primitive0_, _primitive1_, _primitive2_, etc

This is why line 32 I tried to keep comptibility with the current stable version:
[https://www.babylonjs-playground.com/#4AJ16M#15](https://www.babylonjs-playground.com/#4AJ16M#15)

(my code could be probably more cleaned and optimized I suppose)

**Comment by Vinc3r** [comment]
(I see this change is already in the dist/preview what's new: https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md#gltf-loader and also in the breaking changes https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md#breaking-changes

**Comment by deltakosh** [comment]
Ok thanks! Yep this is an optimization to reduce the list of  non renderable meshes
So we're alright:)

**Pull request merged**
